# This example utilizes Mobb with Fortify via GitLab CI/CD pipelines

image:
  name: "node:20"

stages:
  - fortify-sast-scan

workflow: # Run on every merge request
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'web'

fortify-sast-scan-job:
  stage: fortify-sast-scan
  tags:
    - saas-linux-medium-amd64
  script: |
    apt-get update 
    apt install -y openjdk-17-jre-headless maven wget unzip
    wget https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.2.0_x64.zip -O fcs.zip
    unzip fcs.zip
    chmod +x fcs/bin/scancentral
    ls -la
    pwd
    ./bin/scancentral package -bt mvn -o fortify_package.zip



