image:
  name: "node:latest"

stages:          # List of stages for jobs, and their order of execution
  - security-scan
  - mobb-autofix

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


security-scan-job:       # This job runs in the build stage, which runs first.
  stage: security-scan
  tags:
    #- desktop
    - saas-linux-medium-amd64
  script: |
    #dir env:
    #dir
    env
    ls
    #npm i snyk
    npx snyk auth $SNYK_TOKEN
    npx snyk code test --json-file-output=report.json

mobb-autofix-job:   # This job only starts when the job in the scan stage fails (vulnerability has been found).
  stage: mobb-autofix
  tags:
    #- desktop
    - saas-linux-medium-amd64
  script:
    - echo "Running Mobb Autofixer"
    - npm i mobbdev
    - npx mobbdev analyze -f report.json -r $CI_PROJECT_URL --ref main --api-key $MOBB_TOKEN
  when: on_failure #this only runs if the scan fails (vulnerability found)