# This example utilizes Mobb with Fortify via GitLab CI/CD pipelines

image:
  name: "ubuntu:latest"

stages:
  - fortify-sast-scan

workflow: # Run on every merge request
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'web'

fortify-sast-scan-job:
  stage: fortify-sast-scan
  tags:
    - saas-linux-medium-amd64
  script: |
    apt-get update 
    apt-get install wget -y
    apt-get install unzip -y
    wget https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.2.0_x64.zip -O fcs.zip
    unzip fcs.zip
    chmod +x bin/scancentral
    ./bin/scancentral