# This example utilizes Mobb with Checkmarx via GitLab CI/CD pipelines

image:
  name: "node:20"

stages:
  - fortify-sast-scan

workflow: # Run on every merge request
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'web'

checkmarx-sast-scan-job:
  stage: checkmarx-sast-scan
  tags:
    - saas-linux-medium-amd64
  script: |
    apt-get update 
    apt-get install openjdk-18-jre-headless -y
    apt-get install maven -y
    apt-get install wget -y
    apt-get install unzip -y
    apt-get install curl -y
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    NODE_MAJOR=18
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/ apt/sources.list.d/nodesource.list
    apt-get update && apt-get install nodejs -y
    wget https://tools.fortify.com/scancentral/Fortify_ScanCentral_Client_21.2.0_x64.zip -O fcs.zip
    unzip fcs.zip
    chmod +x bin/scancentral
    . /bin/scancentral
    
mobb-autofixer-job:
  stage: mobb-autofixer
  tags:
    - saas-linux-medium-amd64
  script:
    - npx mobbdev@latest analyze -f cx_result.json -r $CI_PROJECT_URL --ref $CI_COMMIT_REF_NAME --api-key $MOBB_API_KEY
  when: on_failure # Run Mobb only if there's a finding to fix