trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Mobb-demo

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
  displayName: Install Node 18

- script: |
    npx snyk auth $(SNYK_API_KEY)
    npx snyk code test --sarif-file-output=report.json
    ls -l
  displayName: 'Snyk SAST Scan'

- task: CopyFiles@2
  inputs:
    contents: '_buildOutput/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
  condition: always()
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
  condition: always()

- script: |
    # npx mobbdev@latest analyze -f report.json -r $BUILD_REPOSITORY_URI --ref $BUILD_SOURCEBRANCHNAME --api-key $(MOBB_API_KEY) --ci
  displayName: 'Mobb Autofixer'
  condition: failed()
