trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Mobb-demo

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
  displayName: Install Node 18

- script: |
    npx snyk auth $(SNYK_API_KEY)
    npx snyk code test --sarif-file-output=report.json
  displayName: 'Snyk SAST Scan'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(System.DefaultWorkingDirectory)/*.json
    artifactName: SnykReport
  condition: always()

- script: |
    npx mobbdev@latest analyze -f report.json -r $BUILD_REPOSITORY_URI --ref $BUILD_SOURCEBRANCHNAME --api-key $(MOBB_API_KEY) --ci
  displayName: 'Mobb Autofixer'
  condition: failed()
