trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Mobb-demo

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.x'
  displayName: Install Node 18

- script: |
    npx snyk auth $(SNYK_API_KEY)
    npx snyk code test --sarif-file-output=report.json
    ls -l
  displayName: 'Snyk SAST Scan'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'report.json'
    publishLocation: 'Container'
  condition: always()
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'report.json'
    publishLocation: 'pipeline'
  condition: always()

- script: |
    # npx mobbdev@latest analyze -f report.json -r $BUILD_REPOSITORY_URI --ref $BUILD_SOURCEBRANCHNAME --api-key $(MOBB_API_KEY) --ci
  displayName: 'Mobb Autofixer'
  condition: failed()
